### PR TITLE
A number of improvements

### PR DESCRIPTION
**Pull request by a1exsh**
- directio
- blocksize
- sequential access

### CODE REVIEW

**Comment by benschweizer** [comment]
Hi, direct io mode should be optional it should use os.open and not a 3rd party module; not using direct io is intended as this tests also the filesystem cache, but having an option is good. Greetings Benjamin

**Comment by a1exsh** [comment]
Well, I don't see a benefit in testing the cache, but an option makes sense.

Unfortunately, normal os.read() will fail on file opened in direct mode due
to memory alignment requirement of the system call, so we have to use
directio module.

Cheers!
Alex

**Comment by benschweizer** [comment]
Hi Alex,

to test real world scenarios, testing the cache is fine. So if you can make
this an option and handle import errors, that would be fine.

Greetings
Benjamin

**Comment by a1exsh** [comment]
On Fri, Sep 11, 2015 at 9:05 PM, Benjamin Schweizer <
notifications@github.com> wrote:

> Hi Alex,
> 
> to test real world scenarios, testing the cache is fine. So if you can make
> this an option and handle import errors, that would be fine.

Please see #5.  Not sure if handling import error makes a lot of sense: if
the the user didn't ask for direct IO with the option, it's not used, if
it's not installed or not supported the import error is sort of
self-describing.

## 

Alex

**Comment by benschweizer** [comment]
Ok, let's decide this later;-) It won't do any damage when the option for direct io is off by default

**Comment by a1exsh** [comment]
On Fri, Sep 11, 2015 at 9:14 PM, Benjamin Schweizer <
notifications@github.com> wrote:

> Ok, let's decide this later;-) It won't do any damage when the option for
> direct io is off by default

Yeah, probably a mention that for the option to work, the directio module
needs to be installed, in the help message or readme is enough.

**Pull request merged**
